# Generated by Django 2.2 on 2021-11-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'developer'), (2, 'project_manager'), (3, 'admin')], default=1),
        ),
    ]
