# Generated by Django 2.2 on 2021-11-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker_app', '0002_auto_20211120_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'unassigned'), (2, 'active'), (3, 'review'), (4, 'resolved')]),
        ),
    ]
